# Generated by Django 4.2.11 on 2024-04-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("decription", models.TextField()),
                ("price", models.FloatField()),
                ("brand", models.CharField(max_length=50)),
                ("tag", models.CharField(max_length=50)),
            ],
        ),
    ]
