# Generated by Django 4.2.11 on 2024-04-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trivadatestApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="decription",
            new_name="description",
        ),
    ]
